channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  # default
  - python=3.9
  # main
  - aenum
  - attrs>=22.2
  - click
  - dessinemoi>=23.1.0
  - environ-config
  - importlib_resources
  - joseki>=2.6.0
  - lazy_loader>=0.1
  - matplotlib>=3.3
  - netcdf4
  - numpy
  - pint
  - pinttrs>=23.2.0
  - pooch
  - rich
  - ruamel.yaml
  - scipy
  - sf-hamilton>=1.40
  - shellingham!=1.5.1
  - tqdm
  - typer>=0.9.0
  - xarray>=0.19,!=0.20.*
  # tests
  - pytest
  - pytest-json-report
