channels:
  - eradiate
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  # main
  - aenum
  - attrs>=22.2
  - click
  - dessinemoi>=23.1.0
  - environ-config
  - lazy_loader>=0.1
  - matplotlib>=3.3
  - netcdf4
  - numpy
  - pint
  - pinttrs>=23.2.0
  - portion
  - pooch
  - rich
  - ruamel.yaml
  - scipy
  - shellingham!=1.5.1
  - tqdm
  - typer>=0.9.0
  - xarray>=0.19,!=0.20.*
  # recommended
  - aabbtree
  - astropy
  - iapws
  - ipython
  - ipywidgets
  - jupyterlab
  - python-dateutil
  - seaborn
  # docs
  - autodocsumm
  - myst-parser
  - nbsphinx>=0.9.0
  - sphinx-book-theme>=1.0
  - sphinx
  - sphinxcontrib-bibtex>=2.0
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinx-design
  # dev
  - conda-lock>=1.4
  - pip>=22
  - pip-tools>=6.5
  - setuptools>=61
  # optional
  - pip
  - pip:
    - eradiate_mitsuba==0.0.1rc10
