# This is a basic workflow to help you get started with Actions

name: Docker build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, docker-v2 ]
    tags: [ v*.*.* ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Launch the build
        run: |
          docker-compose -f docker-build.yml build
          VERSION=$(basename $GITHUB_REF) docker-compose -f docker-build.yml build

      - name: Push the images
        run: |
          docker-compose -f docker-build.yml push
          VERSION=$(basename $GITHUB_REF) docker-compose -f docker-build.yml push
